apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: java-springboot-xlrvyoev
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/java-springboot-xlrvyoev:5df0864ff8a9670ccfbafaf714c450d6ddc391de@sha256:23548a6a248868b7fa88640f28df10b879471b4c3039ec0e27231d6b2acd1c55
          name: container-image
